language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
script:
  - mkdir -p tmp
  - phpunit --configuration phpunit.xml.dist
after_script:
  - php vendor/bin/coveralls

cache:
  directories:
    - vendor